---
- name: Create snapshot of an EC2 volume
  hosts: localhost
  collections:
    - amazon.aws
  vars:
    region: ap-southeast-2
#    volume_id: vol-06c37b30d2ac78204
#    instance_id: i-0c3bd154301d0948e
    host_lists:
      rhel1:
        volume_id: vol-06c37b30d2ac78204

  tasks:
    - name: Show dynamic host_vars safely
      debug:
        msg:  "{{ target_host }} is target."
       #  {{ host_lists[target_host].volume_id }}
#    - name: Show dynamic host_vars
#      debug:
#        msg: "Target DB host is {{ host_lists[target_host].volume_id }}"

    - name: Create a snapshot
      ec2_snapshot:
#        volume_id {{ hostvars[host-name]['volume_id'] }}
        volume_id: "{{ host_lists[target_host].volume_id }}"
        region: "{{ region }}"
#        region {{ hostvars[host-name]['region'] }}
        description: "Snapshot created by Ansible"
      register: snapshot_result

    - name: Show snapshot ID
      debug:
        var: snapshot_result.snapshot_id
