---
- name: Create snapshot of an EC2 volume
  hosts: localhost
  collections:
    - amazon.aws
  vars:
    region: ap-southeast-2
    volume_id: vol-06c37b30d2ac78204

  tasks:
    - name: Create a snapshot
      ec2_snapshot:
        volume_id: "{{ volume_id }}"
#        region: ap-southeast-2
        description: "Snapshot created by Ansible"
      register: snapshot_result

    - name: Show snapshot ID
      debug:
        var: snapshot_result.snapshot_id


#    - name: Create a snapshot
#      ec2_snapshot:
#        region: "{{ region }}"
#        instance_id: i-0c3bd154301d0948e
#        device_name: /dev/sdb1
#        description: "Snapshot created by Ansible"
#      register: snapshot_result
