---
- name: Apache server installed
  hosts: rhel1
  become: yes

  tasks:
  - name: latest Apache version installed
    dnf:
      name: httpd
      state: latest

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: copy web.html
    copy:
      src: /root/web.html
      dest: /var/www/html/index.html

